[package]
name = "bp3d-logger"
version = "1.1.0"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
edition = "2021"
description = "A flexible Log implementation intended to be used with BP3D software."
license = "BSD-3-Clause"
repository = "https://gitlab.com/bp3d/logger"
readme = "./README.MD"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
bp3d-fs = "1.0.0"
crossbeam-channel = "0.5.2"
once_cell = "1.10.0"
time = { version = "0.3.7", features = ["formatting", "macros"] }
time-tz = { version = "0.3.1", features = ["system"] }

[features]
